import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: {
		icon: "/assets/images/apple.svg",
	},
};
const roboto = Roboto({ weight: ["400", "700"], subsets: ["greek", "latin"] });
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
